### ISSUE TITLE
ValueError，Trying to set a tensor of shape torch.Size

### ISSUE THREAD

**Issue by weizai** [HelloVision/HelloMeme#22]
ValueError: Trying to set a tensor of shape torch.Size([77, 768]) in "weight" (which has shape torch.Size([77, 512])), this looks incorrect.

**Comment by songkey** [comment]
Could you please provide more information? For example, the complete error log, and if possible, the specific input used.

**Comment by weizai** [comment]
it was solved when i downloaded all the models
